name: AWS Terraform
description: Runs Terraform against HackneyAWS
inputs:
  aws_region:
    description: 'AWS region to use'
    default: 'eu-west-2'
    required: true  
  terraform_state_s3_bucket:
    description: 'S3 bucket for Terraform state'
    required: true
  aws_account:  
    description: 'AWS Account to deploy to'
    required: true
  build_path:
    description: 'Build path that contains the source'
    required: true
  environment:
    description: 'Name of the environemnt to target'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if Terraform S3 Bucket Exists
      id: s3
      run: |
        if aws s3 ls "s3://${{ inputs.terraform_state_s3_bucket }}" 2>&1 | grep -q 'NoSuchBucket'
        then
          aws s3api create-bucket --bucket ${{ inputs.terraform_state_s3_bucket }} --region ${{ inputs.aws_region }}
        fi
      shell: bash
  
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="region=${{ inputs.aws_region }}" -backend-config="bucket=${{ inputs.terraform_state_s3_bucket }}" -backend-config="key=${{ inputs.environment }}/terraform.state"
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"   

    - name: Terraform Apply
      id: apply
      run: terraform plan
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"
