name: AWS Terraform
description: Runs Terraform against HackneyAWS
inputs:
  aws_region:
    description: 'AWS region to use'
    default: 'eu-west-2'
    required: true  
  terraform_state_s3_bucket:
    description: 'S3 bucket for Terraform state'
    required: true
  build_path:
    description: 'Build path that contains the source'
    required: true
  environment:
    description: 'Name of the environemnt to target'
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform S3 Bucket
      id: s3
      run: |
        aws s3api create-bucket --bucket ${{ inputs.terraform_state_s3_bucket }} --region ${{ inputs.aws_region }} --grant-write --acl private

        if echo "${bucketStatus}" | grep 'Not Found';
        then
          echo "Creating new Terraform S3 Bucket"
          aws s3api create-bucket --bucket ${{ inputs.terraform_state_s3_bucket }} --region ${{ inputs.aws_region }}
          
          aws s3api put-object-lock-configuration \
          --bucket my-bucket-with-object-lock \
          --object-lock-configuration '{ "ObjectLockEnabled": "Enabled", "Rule": { "DefaultRetention": { "Mode": "COMPLIANCE", "Days": 50 }}}'
          
          echo "Sleeping 2 minutes for S3 Bucket to become availble"
          sleep 2m     
        elif echo "${bucketStatus}" | grep 'Forbidden';
        then
          echo "Terraform S3 Bucket exists but not owned"
        elif echo "${bucketStatus}" | grep 'Bad Request';
        then
          echo "Terraform S3 Bucket name specified is less than 3 or greater than 63 characters"
        else
          echo "OK: Terraform S3 Bucket exists and is owned";
        fi
      shell: bash
  
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="region=${{ inputs.aws_region }}" -backend-config="bucket=${{ inputs.terraform_state_s3_bucket }}" -backend-config="key=${{ inputs.environment }}/terraform.state"
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"   

    - name: Terraform Apply
      id: apply
      run: terraform plan
      shell: bash
      working-directory: "${{ inputs.build_path }}/terraform"
