name: Test Project DevScratch
env:
  aws_region: "eu-west-2"
  aws_account: ${{ secrets.AWS_ACCOUNT_DEVSCRATCH }}
  terraform_state_key: "test-project"  
  build_path: "projects/test"
  environment: "dev"
  
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $build_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $build_path

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.aws_region }}
        role-external-id: "arn:aws:iam::${{ env.aws_account }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}"
    - name: Run AWS Terraform
      uses: ./.github/actions/aws-terraform
      with:
        aws_region: ${{ env.aws_region }}
        terraform_state_key: ${{ env.terraform_state_key }}
        build_path: ${{ env.build_path }}
        environment: ${{ env.environment }}
