name: Test Project Dev
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $terraform_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $terraform_path

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/aws-terraform
      with:
        terraform__state_s3_bucket_name: "my_state_bucket"
        aws_account: "dev_scratch"
        aws_iam_role: ""
        terraform_path: $terraform_path
        environment: "dev"
