name: Test Project Dev
env:
  terraform__state_s3_bucket_name: "my_state_bucket"
  aws_account: "dev_scratch"
  aws_iam_role: ""
  terraform_path: "projects/test/terraform"
  environment: "dev"
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $terraform_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $terraform_path

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/aws-terraform
      with:
        #aws_account: $aws_account
        #aws_iam_role: $aws_iam_role
        #terraform_path: $terraform_path
        terraform_path: "projects/test/terraform"
        #environment: $environment
