name: Trigger Test Project Dev
env:
  # These should be the only things you need to change!
  build_path: "projects/test"
  deploy_env: "dev"
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $build_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $build_path

jobs:
  trigger-build:
    name: Trigger AWS Terraform Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "build_path": "${{ env.build_path }}", "deploy_env": "${{ env.deploy_env }}" }'
