name: Test Project Dev
env:
  aws_s3_bucket: "test-bucket"
  aws_account: ""
  aws_iam_role: ""
  build_path: "projects/test"
  environment: "dev"
  
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $build_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $build_path

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/aws-terraform
      with:
        aws_s3_bucket: "${{ env.aws_s3_bucket }}"
        aws_account: "${{ env.aws_account }}"
        aws_iam_role: "${{ env.aws_iam_role }}"
        build_path: "${{ env.build_path }}"
        environment: "${{ env.environment }}"
