name: Test Project Dev
env:
  aws_account: ""
  aws_iam_role: ""
  terraform_path: "projects/test"
  environment: "dev"
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    paths:
      - $terraform_path
  pull_request:
    branches: [ $default-branch ]
    paths:
      - $terraform_path

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/aws_terraform
      with:
        aws_account: $aws_account
        aws_iam_role: $aws_iam_role
        terraform_path: $terraform_path
        environment: $environment
